config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = current_user.books.new(book_params)
    # @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title)
  end
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_back.html.erb
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1 class="title">Books</h1>
<%= link_to 'New Book', new_book_path, class: "button is-primary is-outlined" %>
<table class="table" style="width: 100%;">
  <tr>
    <th>Title</th>
    <th colspan="3"></th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= link_to 'Show', book_path(book) %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy',
              book_path(book),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_with scope: :book, url: books_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <%= form.submit %>
<% end %>

<%= render 'books/back' %>

app/views/books/show.html.erb
<h1 class="title"><%= @book.title %></h1>


<%= render 'books/back' %>

app/views/home/index.html.erb
<h1>Welcome to home!</h1>
<p>There is nothing</p>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="notification is-success">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="notification is-danger">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item" %>
      <%= link_to "Book", books_path, class: "navbar-item" %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">

        <% if user_signed_in? %>
          <%= link_to current_user.email, edit_user_registration_path, class: 'navbar-item' %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'navbar-item' %>
        <% else %>
          <div class="buttons">
            <%= link_to new_user_registration_path, class: "button is-primary" do %>
              <strong>Sign up</strong>
            <% end %>
            <%= link_to "Log in", new_user_session_path, class: "button is-light" %>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDevis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="section">
      <div class="container">
        <%= render "layouts/messages"%>
        <div class="content">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>